AirshipWeb/airship-website

- site/authors/ryan-vanwyk.md
> Add author: Ryan Van Wyk

- site/blog/elevating-devops-and-enabling-5g-with-airship.md
> Re-publish Amy's blog

- site/authors/alan-meadows.md
> Add author: Alan Meadows

- site/authors/rodolfo-pacheco.md
> Add author: Rodolfo Pacheco

- site/authors/matt-mceuen.md
> Add author: Matt McEuen

- site/authors/pete-birley.md
> Add author: Pete Birley

- site/community/index.md
> Update with videos from Denver Summit

- site/authors/ryan-meadows.md
- site/authors/ryan-vanwyk.md
> Added author file with 3 names, and revised one author file

- site/blog/airship-blog-series-1-evolution-towards-2.0.md
> Airship 2.0 Blog Series 1

- site/authors/rodolfo-meadows.md
> Add a New Author File for Both Rodolfo Pacheco and Alan Meadows

- site/community/index.md
- site/index.md
Hey! Airship-in-a-Bottle has a new home in our Treasuremap repository. This PR updates the location.
> Update airship-in-a-bottle location

- site/blog/airship-blog-series-2-an-educated-evolution.md
> Airship Blog 2 - An Educated Evolution

- site/.vuepress/components/bar.vue
> Fix the Link of "View Sessions" on Top Bar of Home Page

- gatsby-config.js
- src/style/modules/_base.scss
Signed-off-by: Tomás Castillo <tcastilloboireau@gmail.com>
> Improves code styling

- src/pages/blog/2020-airship-tc-election.md
> 2020-2021 Technical Committee Election Results

- src/pages/blog/ironic-airship2-case-study.md
> Initial draft of Ironic Airship Case Study

- src/pages/blog/2020-airship-wc-election.md
> Initial draft of WC election results

- src/templates/index-page.js
> Add hyperlink to community info wiki

- src/components/Footer.js
- src/pages/community/index.md
- src/pages/supporters/index.md
- Update to text
- General content and URL updates
> OSF Branding upadtes

- src/pages/blog/airship-update-december-2020.md
> Minor typo correction for Kubevirt

- gatsby-browser.js
- gatsby-ssr.js
- src/components/SEO.js
- src/pages/blog/index.js
- src/templates/community-page.js
- src/templates/index-page.js
- src/templates/software-page.js
- src/templates/supporters-page.js
- src/templates/users-page.js
Signed-off-by: Tomás Castillo <tcastilloboireau@gmail.com>
> Fix twitter cards and OG tags

- src/components/Subscribe.js
- src/style/modules/_search.scss
* Replaces the form with a button that opens a popup to sign up to news, so the user isn't redirected and stays on the page.
Signed-off-by: Tomás Castillo <tcastilloboireau@gmail.com>
> change subscription form for link button

- src/pages/blog/airship2-released.md
> Airship2 GA Announcement
